### ISSUE TITLE
Problem 03

### ISSUE THREAD

**Issue by nikiqta** [Tech-Module-Jan-2018-THE-BESTT/programming-fundamentals#2]
Problem 03. has an issue that prevent the code from execution , the using System it is not written correctly.
![capture](https://user-images.githubusercontent.com/33606495/37869990-3ea873e4-2fbb-11e8-869f-9a8f3708a5c7.PNG)

**Comment by alphastation** [comment]
Thanks for raising this issue. Now it is resolved!

**Comment by alphastation** [comment]
![capture3](https://user-images.githubusercontent.com/26443203/37874100-bc4d8bae-301f-11e8-9af3-210b2c84af51.PNG)
